return {
    Edition = "Standard",
    SortMoviesByGenre = true,
    GrabDeliveryBoxes = true,
    MarkMatchingTapes = true,
    CollectMarkedTapes = true,
    ReorganizeReturnPad = true,
    GrabBoxKey = "F5",
    MarkTapeKey = "F6",
    CollectTapeKey = "F7",
    DeliveryBoxMaxDistance = 700,
    CollectionCapacity = 48,
    InitialStateDelayMs = 2500,
    BaselinePollIntervalMs = 1000,
    AutoDumpAfterInventoryChange = false,
    DebugLogging = false,
}
